### ISSUE TITLE
Conform approach for passing native SDK generated errors on

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-flutter#10]
See [this thread](https://github.com/ably/ably-flutter/pull/5#discussion_r419159180) for the discussion that prompted the creation of this issue.

Please ping me when starting work on this so we can discuss approach at that time.

**Comment by ikbalkaya** [comment]
I checked the related discussion linked to this issue. As far as I understood, @mattheworiordan pointed out fragile situation on passing types around in open. Should I assume that this issue attempts to address this (Strenghtening message passing.  type serialisation, deserialisation etc.) @QuintinWillison ?

**Comment by QuintinWillison** [comment]
I don't think this issue is specific or focussed enough to add value now, especially given we [came out of preview](https://github.com/ably/ably-flutter/releases/tag/v1.2.0) August 2021.
