### ISSUE TITLE
Make this SDK ready for the first non-preview release 

### ISSUE THREAD

**Issue by kavalerov** [ably/ably-flutter#102]
Acceptance criteria: 

* \[ ] Readme updated with Known Limitations section

The following features work:

* \[x] [Pub/Sub](https://ably.com/documentation/realtime/messages#messages)
* \[x] [Presence](https://ably.com/documentation/realtime/presence)
* \[x] [History](https://ably.com/documentation/realtime/history)
* \[ ] [Transient Publishing](https://ably.com/documentation/realtime/channels#channel-lifecycle)
* \[x] [Reconnect on failed auth](https://ably.com/documentation/realtime/usage#client-options)
* \[x] [MsgPack binary protocol](https://ably.com/documentation/realtime/usage#client-options)
* \[ ] [JWT auth](https://ably.com/documentation/core-features/authentication#token-authentication)
* \[x] [fromEncoded function](https://ably.com/documentation/realtime/messages)
* \[ ] [Message extras](https://ably.com/documentation/realtime/types#message)
* \[x] [ErrorInfo URLs to help debug issues](https://ably.com/documentation/realtime/types#error-info)
* \[x] [Message Delta Compression](https://ably.com/documentation/realtime/channels/channel-parameters/deltas)
* \[ ] [Symmetric encryption](https://ably.com/documentation/realtime/encryption)
* \[x] [REST Channel Publish](https://ably.com/documentation/rest/channels#getting-started)
* \[x] [REST History](https://ably.com/documentation/rest/history) 
* \[x] [REST Presence (get state)](https://ably.com/documentation/rest/presence)

**Comment by AndyNicks** [comment]
Done. PR is in review

**Comment by AndyNicks** [comment]
Merged #3770 into main.

**Comment by tiholic** [comment]
@AndyNicks @kavalerov 

Updated the checklist:

- [x] fromEncoded function
- [x] Reconnect on failed auth

Message extras is being improvised here along with delta compression #123 (supposed to go under stage 2 release)

Please re-open if you feel necessary

**Comment by tiholic** [comment]
Transient publishing is handled, but `errorInfo` isn't being updated on `channel` instance currently.

**Comment by AndyNicks** [comment]
Sill in progress
