### ISSUE TITLE
Custom Transport Parameters (Params)

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-flutter#108]
The absence of this feature is a known limitation of this plugin.

See:

- Docs: [ClientOptions](https://ably.com/documentation/realtime/usage#client-options)' optional `transportParams` attribute
- [RTC1f](https://docs.ably.io/client-lib-development-guide/features/#RTC1f): the `transportParams` attribute of `ClientOptions` (for Realtime clients only)

**Comment by ikbalkaya** [comment]
I am not able to point out the particular PR but I can see that this attribute has been added in 18/06/2021. Should we close this issue @QuintinWillison ?

**Comment by ikbalkaya** [comment]
> Docs: ClientOptions' optional transportParams attribute
On Dart code ClientOptions class this property is already there

**Comment by QuintinWillison** [comment]
Is it tested? In other words, do you have confidence it's implemented and proven working?

**Comment by ikbalkaya** [comment]
I haven't checked to that extent unfortunately, I just checked the existence.

**Comment by QuintinWillison** [comment]
ok, thanks. Until we have confidence in that then let's leave this issue open.
