### ISSUE TITLE
Delta Message Compression support not listed in the Known Limitations

### ISSUE THREAD

**Issue by kavalerov** [ably/ably-flutter#125]
Does ably-flutter currently support Delta Message Compression? I know it is not listed in the readme, but I see the PR (https://github.com/ably/ably-flutter/pull/123) is still open. @tiholic / @QuintinWillison ?

If this is correct, @AndyNicks we will need to update the readme (add it to the Known Limitations section) and also correct the feature support matrix once again.

**Comment by tiholic** [comment]
@kavalerov DeltaCompression is still not available for flutter.
#123 aims to add support for delta extension in `MessageExtras` and it may need wait for an update from `ably-java`.

ref: [discussion 1](https://ably-real-time.slack.com/archives/C0178QGC093/p1620149982091800), [discussion 2](https://ably-real-time.slack.com/archives/C0178QGC093/p1621968114034400)

**Comment by AndyNicks** [comment]
I added Delta Compression to Known Limitations section of README as well as updated the Matrix

**Comment by kavalerov** [comment]
Considering the above I think we can close this issue.
