### ISSUE TITLE
Could not find method coreLibraryDesugaring() for arguments

### ISSUE THREAD

**Issue by rezashamdani** [ably/ably-flutter#130]
Hi,

I create an application in flutter and can run the application for ios, but when try to run it on android problem arise;

`1: Task failed with an exception.
-----------
* Where:
Build file '/Users/rezash/Sites/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.0-preview.2/android/build.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':ably_flutter'.

> Could not find method coreLibraryDesugaring() for arguments [com.android.tools:desugar_jdk_libs:1.1.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
`

I have tried to update my flutter to version Flutter 2.2.2 , but the problem still there.

![image](https://user-images.githubusercontent.com/3622787/122350427-68b9d880-cf77-11eb-886c-8740c3a6ee87.png)
Attached, my flutter doctor result.

Please help, 

Thanks.

**Comment by heshanka** [comment]
It might be related to your gradle version. Did you upgrade?

**Comment by rezashamdani** [comment]
i might do that earlier.

![image](https://user-images.githubusercontent.com/3622787/122369427-62802800-cf88-11eb-87ea-aacbdb09daea.png)
this from android/.gradle

**Comment by rezashamdani** [comment]
what gradle version should be used then?

**Comment by rezashamdani** [comment]
For those with similar problem;

load the android visual studio code from the android folder of your flutter ;

From this information (https://developer.android.com/studio/releases/gradle-plugin?hl=id):
<img width="684" alt="image" src="https://user-images.githubusercontent.com/3622787/122528131-34f9b400-d046-11eb-85d3-9371efef77e9.png">



Locate the file build.gradle , and make sure version gradle being use is matched
![image](https://user-images.githubusercontent.com/3622787/122527508-92413580-d045-11eb-8b5c-5fda29a703bb.png)

![image](https://user-images.githubusercontent.com/3622787/122527817-e1876600-d045-11eb-9813-056ec5f3b6e2.png)
From my machine, using the `com.android.tools.build:gradle:4.2.1` with `distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-all.zip` and then click `Sync Project with Gradle Files` will make the problem go away and you can run/debug the application.

thanks.

**Comment by ben-xD** [comment]
Hey @rezashamdani, it's great you fixed it. I guess you had used an older version gradle/ Android gradle plugin in your project, and updating it fixed it. 

Can you say what versions you were using previously?
