### ISSUE TITLE
Simplify channel subscribe API

### ISSUE THREAD

**Issue by tiholic** [ably/ably-flutter#131]
Realtime channel subscription filter takes `name` or `names` as named arguments.

[RTL7](https://docs.ably.io/client-lib-development-guide/features/#RTL7) says we can subscribe to a single name argument, while [TS spec](https://github.com/ably/ably-js/blob/b1ef7473d5b8ca9a3a94de543f547ccfd6e6e71d/ably.d.ts#L544) definition users a union type of string and array to define the name/names parameter.

ably-java supports [subscribe with `name`](https://github.com/ably/ably-java/blob/main/lib/src/main/java/io/ably/lib/realtime/ChannelBase.java#L634) or with [multiple `names`](https://github.com/ably/ably-java/blob/main/lib/src/main/java/io/ably/lib/realtime/ChannelBase.java#L657)

While ably-cocoa seems to support just `name`

ref: https://github.com/ably/ably-flutter/pull/123#discussion_r649080709

**Comment by ikurek** [comment]
I've taken a look at this and here's how the subscribe methods looks like in Dart SDK:

```dart
Stream<Message> subscribe({String? name, List<String>? names}) {
    final subscribedNames = {name, ...?names}.where((n) => n != null).toList();
    return listen<Message>(PlatformMethod.onRealtimeChannelMessage, {
        TxTransportKeys.channelName: this.name,
    }).where((message) =>
        subscribedNames.isEmpty ||
        subscribedNames.any((n) => n == message.name));
  }
```

Internally, Flutter SDK doesn't filter by names using `cocoa` or `java` methods - it subscribes without filters, and then filters messages on Dart side. Thanks to that, in case of Dart SDK we can use both approaches without problems, but we have to decide which one we want to go with: 

    1. single `name` param (aligned to specs definition)
    2. both `name` and `names` (aligned to Java and TS)

Personally, I don't see a reason to reduce the functionality now, so I think we can just leave it as-is. @QuintinWillison @ikbalkaya what do you think?

**Comment by QuintinWillison** [comment]
I agree. This feels like a non-issue.
