### ISSUE TITLE
Conform hashCode implementations

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-flutter#132]
Avoid unnecessary steps like concatenating component hash codes as a string to then convert back to hash code again... this should all be basic maths.

Triggered by [this comment](https://github.com/ably/ably-flutter/pull/123#discussion_r650793251).

**Comment by tiholic** [comment]
@QuintinWillison if we go with integer addition, it could potentially lead to wrong hashCode values as the sub could be same for different hashcode additions.

_ex:
`extrasmap.hashCode = 123 and deltas.hashCode = 321`  would sum up to 444.
Also, `extrasmap.hashCode = 200 and deltas.hashCode = 244`_ would sum up to the same.

Hope I'm not missing any other implications here.

**Comment by QuintinWillison** [comment]
There will always be hash code clashes, so that's perfectly normal. There's no definition of "wrong" when it comes to hash codes, though that is [a common misconception](https://eclipsesource.com/blogs/2012/09/04/the-3-things-you-should-know-about-hashcode/) - they are never guaranteed to be unique for every different object construction from a given class.
