### ISSUE TITLE
Update to latest ably-android version

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-flutter#147]
We've released [version 1.2.7](https://github.com/ably/ably-java/releases/tag/v1.2.7).

At the time of writing this issue this codebase [targets version 1.2.6](https://github.com/ably/ably-flutter/blob/6790ed2206852af0e7148cca36071aa9c6813ddf/android/build.gradle#L25).

Version 1.2.7 adds `Ably-Agent` support, so it would make sense to also implement https://github.com/ably/ably-flutter/issues/100 in the scope of any release that includes a fix for this issue.

**Comment by ben-xD** [comment]
This was done in https://github.com/ably/ably-flutter/pull/162 to avoid runtime crashes. See ably-java's issue: https://github.com/ably/ably-java/issues/597

> It's now even worse, in firebase messagaging library 22.0.0 the whole FirebaseInstanceId has been removed and you will get a runtime crash with Ably.

Agent header https://github.com/ably/ably-flutter/issues/100 was not done though, since that is a separate issue.
