### ISSUE TITLE
Deviation from Ably SDK APIs

### ISSUE THREAD

**Issue by tiholic** [ably/ably-flutter#15]
This issue is a result of review from PR #6

https://github.com/ably/ably-flutter/pull/6#pullrequestreview-418489247
https://github.com/ably/ably-flutter/pull/6#discussion_r430559986

**Comment by tiholic** [comment]
@QuintinWillison I think we can link this Issue to https://github.com/ably/ably-flutter/pull/18 and close?

**Comment by QuintinWillison** [comment]
I agree, @tiholic - thanks. 😁
