### ISSUE TITLE
Should we implement EventEmitter?

### ISSUE THREAD

**Issue by tiholic** [ably/ably-flutter#16]
Current implementation of event streams using "flutter streams channel" plugin which will create an instance of Event Channel on platform side.

[This discussion](https://github.com/ably/ably-flutter/pull/6#discussion_r420711550) sheds some light on different approaches that can be followed to implement the same along with caveats of each approach.

**Comment by ikbalkaya** [comment]
Looks like this was already done using Streams channel. Should this be closed @QuintinWillison 🤔

**Comment by QuintinWillison** [comment]
The referenced discussion was had very early on in the development of this plugin. We've been released (out of preview) for nearly six months now, and we've not seen any evidence that [EventEmitter](https://ably.com/documentation/client-lib-development-guide/features/#eventemitter) is required or makes idiomatic sense for Dart / Flutter.
