### ISSUE TITLE
Write symmetric encryption tests

### ISSUE THREAD

**Issue by ben-xD** [ably/ably-flutter#205]
https://github.com/ably/ably-flutter/pull/192 introduces symmetric encryption. We should write tests for this asap.

**Comment by QuintinWillison** [comment]
It looks like this lack of testing has come back to bite us: https://github.com/ably/ably-flutter/issues/296

**Comment by QuintinWillison** [comment]
@ikurek will work on this after https://github.com/ably/ably-flutter/issues/332.
