### ISSUE TITLE
iOS build errors after updating to ably 1.2.3

### ISSUE THREAD

**Issue by heshanka** [ably/ably-flutter#206]
Flutter Version: 2.5.3 channel stable

Error output from Xcode build:
        ABAddressBookRequestAccessWithCompletion(ABAddressBookCreate(), ^(bool granted, CFErrorRef error) {
        ABAddressBookRequestAccessWithCompletion(ABAddressBookCreate(), ^(bool granted, CFErrorRef error) {
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:23:13: error: 'case' label in a 'switch' should have at least one executable statement
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:24:13: error: 'case' label in a 'switch' should have at least one executable statement
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:25:13: error: 'case' label in a 'switch' should have at least one executable statement
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:26:13: error: 'case' label in a 'switch' should have at least one executable statement
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:27:13: error: 'case' label in a 'switch' should have at least one executable statement
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:28:13: error: 'case' label in a 'switch' should have at least one executable statement
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:29:13: error: 'case' label in a 'switch' should have at least one executable statement
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:30:13: error: 'case' label in a 'switch' should have at least one executable statement
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:31:13: error: 'case' label in a 'switch' should have at least one executable statement
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:32:13: error: 'case' label in a 'switch' should have at least one executable statement
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:33:13: error: 'case' label in a 'switch' should have at least one executable statement
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:51:78: error: cannot find type 'EventMessage' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:15:18: error: cannot find 'CodecType' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:20:18: error: cannot find 'CodecType' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:21:18: error: cannot find 'CodecType' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:22:18: error: cannot find 'CodecType' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:23:18: error: cannot find 'CodecType' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:24:18: error: cannot find 'CodecType' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:25:18: error: cannot find 'CodecType' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:26:18: error: cannot find 'CodecType' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:27:18: error: cannot find 'CodecType' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:28:18: error: cannot find 'CodecType' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:29:18: error: cannot find 'CodecType' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:30:18: error: cannot find 'CodecType' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:31:18: error: cannot find 'CodecType' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:32:18: error: cannot find 'CodecType' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:33:18: error: cannot find 'CodecType' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:54:33: error: cannot find 'TxAblyEventMessage_registrationHandle' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:80:61: error: value of optional type 'Bool?' must be unwrapped to a value of type 'Bool'
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:81:71: error: value of optional type 'String?' must be unwrapped to a value of type 'String'
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:82:79: error: value of optional type 'String?' must be unwrapped to a value of type 'String'
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:83:77: error: value of optional type 'Bool?' must be unwrapped to a value of type 'Bool'
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:84:89: error: value of optional type 'Bool?' must be unwrapped to a value of type 'Bool'
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:85:81: error: value of optional type 'Bool?' must be unwrapped to a value of type 'Bool'
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:86:79: error: value of optional type 'Bool?' must be unwrapped to a value of type 'Bool'
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:88:77: error: value of optional type 'String?' must be unwrapped to a value of type 'String'
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:89:103: error: value of optional type 'Bool?' must be unwrapped to a value of type 'Bool'
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:90:81: error: 'Any?' is not convertible to '[String]?'
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:93:98: error: 'Any?' is not convertible to 'String'
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:94:57: error: cannot find 'FLUTTER_PACKAGE_PLUGIN_VERSION' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:104:14: error: cannot find 'TxLogLevelEnum_verbose' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:105:14: error: cannot find 'TxLogLevelEnum_debug' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:106:14: error: cannot find 'TxLogLevelEnum_info' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:107:14: error: cannot find 'TxLogLevelEnum_warn' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:108:14: error: cannot find 'TxLogLevelEnum_error' in scope
            case TxLogLevelEnum_error: return .error
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:109:14: error: cannot find 'TxLogLevelEnum_none' in scope
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:123:31: error: no exact matches in call to initializer 
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:151:39: error: value of optional type 'String?' must be unwrapped to a value of type 'String'
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:151:55: error: cannot convert value of type 'NSDate?' to expected argument type 'Date?'
    /Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/ably_flutter-1.2.3/ios/Classes/codec/AblyFlutterReader.swift:151:72: error: cannot convert value of type 'NSDate?' to expected argument type 'Date?'
Encountered error while building for device.

**Comment by ben-xD** [comment]
Hey @heshanka, that file should not be in the release at all. Unfortunately, the github release didn't contain this file, but for some reason the pub.dev release did. 

This has been fixed, and will be available in the [latest release (probably available in less than 1 hour), v1.2.4](https://github.com/ably/ably-flutter/pull/211) which should work without this error.

**Comment by heshanka** [comment]
Alright, good to know; Thanks @ben-xD

**Comment by ben-xD** [comment]
If you'd like to use it immediately, in your `pubspec.yaml` you could do:
```
  ably_flutter:
    git:
      url: git://github.com/ably/ably-flutter.git
      ref: release/1.2.4
```

However, this branch will be deleted once the release is made, so you'd have to go back to using `ably_flutter: ^1.2.4`
