### ISSUE TITLE
Remove nesting of AblyMessages

### ISSUE THREAD

**Issue by ben-xD** [ably/ably-flutter#245]
In Platform_object.dart, we have: 

https://github.com/ably/ably-flutter/blob/78144602ab1b63568e3eaea4f79b7035e541231a/lib/src/platform/src/platform_object.dart#L68-L75

Where `message` can either be a nested message or not, depending on the what you pass the method. This makes it more complicated when deserializing on the platform side, since we are not sure if the message being received will be nested or not. This results in a lot of complicated code, and in fact it also tricks Android Studio, resulting in a lot of **errors** in the linter. 

**We should stop nesting AblyMessages.**

I've tried to do this in https://github.com/ably/ably-flutter/pull/199, but I added **three** other unrelated changes (described in that PR). The PR got bigger and bigger, so I should recreate all 4 things in that PR in 4 separate PRs. This branch is also significantly out of date with the latest work done in the repo. 

@QuintinWillison

**Comment by QuintinWillison** [comment]
Poorly defined, making it unclear as to why this change was deemed necessary.
