### ISSUE TITLE
Implement stats Rest and Realtime clients

### ISSUE THREAD

**Issue by ben-xD** [ably/ably-flutter#260]
Implement following methods in Rest and Realtime
https://github.com/ably/ably-flutter/blob/b3cb8bf32efdcca3a314a612bf41950777950846/lib/src/platform/src/realtime/realtime.dart#L104-L105
and

https://github.com/ably/ably-flutter/blob/b3cb8bf32efdcca3a314a612bf41950777950846/lib/src/platform/src/rest/rest.dart#L61

These methods `throw UnimplementedError();`.

**Comment by QuintinWillison** [comment]
To explain why this issue [was closed](https://github.com/ably/ably-flutter/issues/260#event-6139204388), it was a duplicate of https://github.com/ably/ably-flutter/issues/106.
