### ISSUE TITLE
1.2.6 java.lang.NullPointerException when using token auth 

### ISSUE THREAD

**Issue by 1N50MN14** [ably/ably-flutter#272]
So I just upgraded to 1.2.6 to see if the "scary" auth token message has disappeared and test drive encryption but now the app crashes momentarily. Given the below snippet which I've been using pre 1.2.6

```javascript
  final clientOptions = ClientOptions()
    ..clientId = clientId
    ..logLevel = LogLevel.error
    ..autoConnect = false
    ..authMethod = 'POST'
    ..useTokenAuth = true
    ..authCallback = authCb;

  final RealTime realtime = Realtime(options: clientOptions);

  await realtime.connect();
```

The following exception gets thrown causing the app to crash all together:
`E/StreamsChannel#io.ably.flutter.stream(18567): java.lang.NullPointerException: Attempt to read from field 'io.ably.lib.realtime.Connection io.ably.lib.realtime.AblyRealtime.connection' on a null object reference`

**Comment by ben-xD** [comment]
Hi @1N50MN14

Can you provide a reproducible example or provide more information?

**Comment by 1N50MN14** [comment]
@ben-xD #274 is actually caused by hot reloading the app during development, here's exactly code I'm using that causes #274 , nothing fancy:

```javascript
import 'dart:convert';

import 'package:ably_flutter/ably_flutter.dart';

class AblyRT
{
  final Function(String topic, Map<String, dynamic> data) onMessage;

  final String accountId;

  RealtimeChannel? privateDataChannel;

  Realtime? realtime;

  AblyRT({
    required this.onMessage,
    required this.accountId,
  });

  Future<void> connect() async
  {
    await realtime?.close();

    realtime = null;

    final messageData = (Message message)
    {
      Map<String, dynamic> data = {};

      (message.data as Map).forEach((key, value)
      {
        data[key.toString()] = value;
      });

      return data;
    };

    final clientOptions = ClientOptions.fromKey('*****************')
      ..autoConnect = false;

    realtime = Realtime(options: clientOptions);

    await realtime!.connect();

    privateDataChannel = realtime!.channels.get('private:'+accountId);

    privateDataChannel!.subscribe()..listen((message)=>
      onMessage(message.name ?? '', messageData(message)));
  }
}
```
I initialize the class and call `connect()` later on within the app's init life cycle. I call `await realtime?.close();` just to be on the safe side.

When it comes to this issue I'm just adding `authCallback`, `useAuthToken` and the `authCallback` itself per my first report to the above snippet.

**Comment by ben-xD** [comment]
Thanks for all that information @1N50MN14, I'll investigate asap and get back to you.

**Comment by ben-xD** [comment]
It looks like this issue has been fixed after the release. Unfortunately the bug fix was not merged into main by the time the release was made, even though the PR was already ready. I should have been more careful with the PRs. 

If you just taking it for a test drive, you could use an unreleased branch which represents the latest unreleased work in Ably Flutter:
```yaml
  ably_flutter:
    git:
      url: git://github.com/ably/ably-flutter.git
      ref: enhancement/ios-simulator
```

Please let me know how it goes, @1N50MN14

**Comment by 1N50MN14** [comment]
@ben-xD Yup! That fixed both issues! :)

**Comment by 1N50MN14** [comment]
The only thing I'm unable to test is symmetric encryption... the Node.js API doesn't seem to support that for batch requests unless I explicitly send the message to all channels one by one :-( My plan was to pass the same cipher key I'm using server-side to recreate cipher params using the same `getDefaultParams` in ably-flutter (thank for the the code example btw). 

Anyway, this issue is resolved I'm gonna go ahead and close it for now. Many thanks @ben-xD for the quick feedback!
