### ISSUE TITLE
Add linting rules

### ISSUE THREAD

**Issue by tiholic** [ably/ably-flutter#30]
Rules: https://dart-lang.github.io/linter/lints/

Discussion: https://ably-real-time.slack.com/archives/C0178QGC093/p1596456192026600

**Comment by tiholic** [comment]
https://github.com/ably/ably-flutter/pull/20#discussion_r464403047

**Comment by ben-xD** [comment]
https://pub.dev/packages/pedantic has been deprecated. 

> Instead, please see package:lints which is the lint recommendation from the Dart team, or package:flutter_lints which extends that for Flutter. These are better than the Google lint set because they take into account the needs of all Dart users, not just Google engineers.
>
> To migrate away from package:pedantic please see the instructions here.

In the latest release from Flutter, they mentioned https://pub.dev/packages/flutter_lints 

We should switch to use this instead

**Comment by ben-xD** [comment]
Closing this because of the above comment, a new issue has been created: https://github.com/ably/ably-flutter/issues/168
