### ISSUE TITLE
ably-java authCallback flow expects synchronous response

### ISSUE THREAD

**Issue by tiholic** [ably/ably-flutter#31]
According to [ably-java source](https://github.com/ably/ably-java/blob/main/lib/src/main/java/io/ably/lib/rest/Auth.java#L581), authCallback expects a response as a `String` or `TokenDetails` or `TokenRequest`.

Java code can call MethodChannel api to flutter side, but only asynchronously using a `MethodChannel.Response` callback. See: `io.flutter.plugin.common.MethodChannel` in https://api.flutter.dev/javadoc/

**Comment by tiholic** [comment]
@paddybyers 's [comments](https://ably-real-time.slack.com/archives/C0178QGC093/p1596607401047000) on this:

Suppose a Flutter Rest client is initialised with an `authCallback`:

A **REST** operation (or any synchronous operation) should be attempted, and if it fails with a token error (ie an error with a `code` in the range `40140..40159`) then:
- call the `authCallback` for a new token;
- call a new API we're going to have to expose on each library to set the new token;
- retry the request according to the retry policy.

Later we can try to optimise this by having the library check the validity of the token before attempting an operation, but we will need to have retry flow in any case, so let's implement that.


For **Realtime** operations, then a connection can enter the disconnected state and the Reason will indicate whether or not it is a token error. Again, if it is a token error, the client needs to call the callback to get a new token, set the token, and reconnect.

The only use-case that isn't handled by those cases above ^ is in-bound reauthentication: this is where a message is received from the server saying that the token is about to be invalidated, and the library will attempt to renew it before the connection is dropped. We will need a new event to come back from the plugin to the flutter side to indicate that a new token is needed. Again, the callback is called to get a new token, and then that token is set on the plugin.

**Comment by tiholic** [comment]
@paddybyers How about we stop executing further requests once the error with `code` in range `40140..40159` is thrown, queue them and resolve soon after authentication is restored? This could help us avoid multiple auth failures in the time span user code completes authentication.

**Comment by tiholic** [comment]
@paddybyers 

I was able to successfully have a work around for authCallback from Java side. Tried only on Rest so far:

**ably-java**: triggers authCallback
**flutter-java**: initiates a call (**AC1**) to dart side and returns null
**flutter-dart**: issues a new token data in the form of `TokenRequest` or `TokenDetails` or `token` String
**flutter-java**: stores that token data after **AC1** is successful
**ably-java**: triggers authCallback on next message
**flutter-java**: checks for any stored token for the provided Rest client and returns if a token is available


Was expecting auth error in the range of `40140..40159` but even before auth error was thrown, native code checks if a valid token exists and calls authCallback. So if we are returning `null` Java code [throws `80019`](https://github.com/ably/ably-java/blob/main/lib/src/main/java/io/ably/lib/rest/Auth.java#L591) 

Can we consider that error code for **re-trying request**?


Haven't yet tried on iOS side, but: [this](https://github.com/ably/ably-cocoa/search?q=80019&unscoped_q=80019) and [this](https://github.com/ably/ably-cocoa/search?q=ARTCodeErrorAuthConfiguredProviderFailure&unscoped_q=ARTCodeErrorAuthConfiguredProviderFailure) say it throws same error.

**Comment by tiholic** [comment]
>The only use-case that isn't handled by those cases above ^ is in-bound reauthentication: this is where a message is received from the server saying that the token is about to be invalidated, and the library will attempt to renew it before the connection is dropped. We will need a new event to come back from the plugin to the flutter side to indicate that a new token is needed. Again, the callback is called to get a new token, and then that token is set on the plugin.

@paddybyers can you share more details about the inbound authentication?

**Comment by ikbalkaya** [comment]
Looks like @ben-xD has provided an alternative solution to this here https://github.com/ably/ably-flutter/pull/231
Should we close this issue? @QuintinWillison
