### ISSUE TITLE
Sync Gradle-generated `aar`'s version with SDK version

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-flutter#315]
I'm not sure if this is _required_ but it makes me uneasy that we just show `version` as `1.0` in the POM for the built artifacts such as `ably_flutter_release`.

Discovered if you `flutter build aar --no-profile` from root, and then:

```
ably-flutter % cat build/outputs/repo/io/ably/flutter/plugin/ably_flutter_release/1.0/ably_flutter_release-1.0.pom
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.ably.flutter.plugin</groupId>
  <artifactId>ably_flutter_release</artifactId>
  <version>1.0</version>
  <packaging>aar</packaging>
  <dependencies>
    <dependency>
      <groupId>io.ably</groupId>
      <artifactId>ably-android</artifactId>
      <version>1.2.10</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.google.firebase</groupId>
      <artifactId>firebase-messaging</artifactId>
      <version>22.0.0</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

**Comment by ikurek** [comment]
I've investigated this and I don't think there's much we can do. To set the artifact version for AAR builds, flutter recommends using `--build-number` flag like `flutter build aar --build-number 1.2.13`, and apparently, there's no other way to do this.

I'm not entirely sure if it's even a problem for us - as far as I can tell, we do not release AAR anywhere - the release and publish flow only includes a GitHub release with source code, and pub.dev release. Neither of those use AAR files, so I think we don't have to worry about this. @QuintinWillison Let me know if it's okay to close this 🙂

**Comment by QuintinWillison** [comment]
Fair enough. I wasn't sure when I created this issue. Thanks for investigating - let's close this.
