### ISSUE TITLE
Example App should be able to build and run without `ABLY_API_KEY`

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-flutter#316]
See [this internal Slack comment](https://ably-real-time.slack.com/archives/C0178QGC093/p1644236677751649?thread_ts=1644236148.756599&cid=C0178QGC093) from @ikurek which explained to me that the current incantation required to even get the example app _built_ is this:

    flutter run --observatory-port 8888 --disable-service-auth-codes --dart-define=ABLY_API_KEY=<api_key>

When this project was started out, @tiholic and I engineered a mechanism whereby an API key could be auto-provisioned from our sandbox environment. That was removed recently. I would like it to be reintroduced, especially for those wishing to experiment with this SDK without involving a complex Ably setup (e.g. when push notifications are _not_ needed).

Sure, it's handy to _optionally_ be able to build with a `ABLY_API_KEY` up-front - but that cannot be the default as it presents too much friction for the original intention of the example app as a smoke test / proof of life.

**Comment by ikurek** [comment]
To clarify - the application builds and runs fine without the specified SDK key. It just doesn't generate the key on it's own, so without this parameter it runs, but is mostly useless, since no options are available for the user to try out
