### ISSUE TITLE
Ably interferes with firebase_messaging

### ISSUE THREAD

**Issue by 1N50MN14** [ably/ably-flutter#346]
My use case is that I wish push notifications to be handled directly via firebase_messaging.  Not only that Ably is catching those notifications but it's also throwing an exception `type 'Null' is not a subtype of type 'String' in type cast` in Ably's own Notification class (notification.dart L10) here:

```
factory Notification.fromMap(Map<String, dynamic> map) => Notification(
      map[TxNotification.title] as String, map[TxNotification.body] as String?);
}
```

Which doesn't make sense anyway because title can be empty per the FCM specs (say data messages) and you can fall back to an empty string, even better, make notification handling optional.

EDIT: Adding the block to ApplicationManifest per PushNotifications.md doesn't work, to me at least, it throws an error `The prefix "tools" for attribute "tools:node" associated with an element type "receiver" is not bound.`.

**Comment by ikurek** [comment]
I think you're missing a namespace for the `tools` prefix in your `AndroidManifest.xml`. Please, add `xmlns:tools="http://schemas.android.com/tools"` as an XML namespace and let me know if that solves the issue 🙂

**Comment by 1N50MN14** [comment]
@ikurek YES that did it!! Thank you very much! :) One quick question, is there anything that I need to on iOS to make sure Ably behaves the same there as well?

Many thanks!!

**Comment by ikurek** [comment]
@1N50MN14 I don't think so, on iOS Ably uses APNS instead of FCM, so everything should work fine 🙂 I'm closing the issue, since it seems to be solved.
