### ISSUE TITLE
typed Message#data

### ISSUE THREAD

**Issue by tiholic** [ably/ably-flutter#35]
Currently the property `data` in `Message` (Rest/Realtime publishable message) is of type Object, which could allow users to pass `int`, `double`, `bool` and other primitive types (as per OOP) which are not supported to be sent over the wire as per Ably SDK.

A fail fast approach would be to have data as Union type (not supported by dart yet, but probably soon https://github.com/dart-lang/language/issues/546) or have an interface that could take allow only allowed types as different named arguments which would be a deviation from spec.

```
Message(data: MessageData(map: {}))
Message(data: MessageData(list: []))
Message(data: MessageData(str: "message-data"))
```

See this thread for discussion https://github.com/ably/ably-flutter/pull/21#discussion_r467754330

**Comment by zoechi** [comment]
I looked a bit into this but haven't found something I'm excited about

With assert and generic types this would add at least some runtime checking

```dart
class Message<T> {
  T data;
  Message(this.data) : assert(T == int || T == double || T == bool) {
    print('Constructor: $T $this $data');
  }

  static Message fromValue(Object value) {
    assert(value is int || value is double || value is bool);
    if (value is int) {
      return Message<int>(value);
    } else if (value is double) {
      return Message<double>(value);
    } else if (value is bool) {
      return Message<bool>(value);
    } else {
      throw AssertionError(
          'Above assert or if cases do not cover "${value.runtimeType}"');
    }
  }
}

void main() {
  var msg1 = Message<int>(1);
  // var msg2 = Message<String>('foo'); // asertion error at runtime
  var msg3 = Message(true);
  // var msg4 = Message('foo'); // assertion error at runtime

  // This is the case I added the fromValue function for
  Object v = 3;
  // var msg5 = Message(v); // assertion error at runtime

  // var msg6 = Message<String>(5); // assertion error at runtime
  Object w = 4;
  var msg7 = Message.fromValue(w);
  print(msg7);

  var messages = [msg1, msg3, msg7];
  print(messages);
}
```
(output)
```
dart --enable-asserts test/msg.dart 
Constructor: int Instance of 'Message<int>' 1
Constructor: bool Instance of 'Message<bool>' true
Constructor: int Instance of 'Message<int>' 4
Instance of 'Message<int>'
[Instance of 'Message<int>', Instance of 'Message<bool>', Instance of 'Message<int>']
```

Typed getters for each supported value type.
But this also only provides runtime checks.
The only advantage is IMHO discoverability where the auto-completion list suggests what types are supported,
otherwise it might also be confusing in that developers expect to always get a value of that type when such a getter exists, while they'll just get a runtime error if they use the wrong accessor like if they used `var x = msg.data as int`.

```dart
class Message {
  Object data;
  Message(this.data) : assert(data is bool || data is int || data is double);

  bool get boolData => data as bool;
  int get intData => data as int;
  double get doubleData => data as double;
}

void main() {
  var msg1 = Message(5);
  var msg2 = Message('foo');
  var i = msg1.intData;
}
````

I would at least add a constructor with asserts that check for supported types in such classes (and setters if applicable) like done in the first example.

**Comment by tiholic** [comment]
Yeah even though there is no build time advantage with this approach, this could give more visibility to someone who browses the source to understand API while development.

What do you think @QuintinWillison ?

**Comment by zoechi** [comment]
Right, I think this is better than doc comments 
because compiler or bug reports will trip you off early 
if the asserts are not up-to-date, while docs are very patient

**Comment by QuintinWillison** [comment]
My preference would be to avoid exposing `Object` at all, making the type returned by `message.data` a new interface specific to our Flutter/Dart API. I would like to see code that consumes these messages looking like:

```dart
var stringData = message.data.asString();
```

or even:

```dart
var stringData = message.data.asString;
```

but, then again, might not [UnmodifiableByteBufferView](https://api.dart.dev/stable/2.9.2/dart-typed_data/UnmodifiableByteBufferView-class.html) be of use here as a possible type for `message.data` to return? [typed_data](https://api.dart.dev/stable/2.9.2/dart-typed_data/dart-typed_data-library.html) looks like it's a core library, or am I poking around in areas I know nothing about (again)? 😆

**Comment by zoechi** [comment]
I don't think bytes provide any advantage. If my typed suggestions are not what you want ,`Object` is probably the best option.

**Comment by tiholic** [comment]
A new class `MessageData` introduced to validate data passed in case of `channel#publish`, `channel#presence#enter`, `channel#presence#update` and `channel#presence#leave` APIs with zero changes to exposed API, there by conforming to spec,

Ref commit: https://github.com/ably/ably-flutter/commit/278bd066861e7d8a1273ad935347358888460f9f#diff-a28644e6e9093a8e97bc462f669278974c84c9dfacd803bd332ba289742f2589
