### ISSUE TITLE
Sort named constructor parameters alphabetically

### ISSUE THREAD

**Issue by ikurek** [ably/ably-flutter#351]
Some classes like `ClientOptions` or `TokenDetails` use named constructor parameters, but currently they're not put in any logical order. It may be good to keep named parameters of constructors in a specific order, for example sorted alphabetically. This would add some consistency across the codebase

I've checked if there's a lint rule available for that, but there doesn't seem to be any static analysis solution available

**Comment by QuintinWillison** [comment]
I wonder if we could write our own linter for this. 🤔

**Comment by ikurek** [comment]
@QuintinWillison Sadly, Dart linter doesn't support custom rules yet, there's a really long discussion about that here https://github.com/dart-lang/linter/issues/697. We would need to write the linter from scratch 😞
