### ISSUE TITLE
Update dartdoc usage on CI

### ISSUE THREAD

**Issue by ikurek** [ably/ably-flutter#410]
Currently, we're using `dartdoc` as a package, to generate docs on CI. The execution requires activating the `dartdoc` package with pub, and then calling it to generate the docs like this:

```bash
flutter pub global activate dartdoc
dartdoc .
```

Since `dartdoc` is already included in the base Flutter tooling (see https://pub.dev/packages/dartdoc#installation) we can skip the activation part and execute `dartdoc` directly from Flutter instalation like this:

```bash
dart doc .
```

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1903) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Oh, that's nice! ... either I was missing something fundamental when I originally implemented the doc build workflow, or the inclusion of dartdoc as-standard is a recent innovation.

Regardless, this would be a nice incremental improvement. 😁
