### ISSUE TITLE
[ably-flutter] Implement no-connection-serial

### ISSUE THREAD

**Issue by jamienewcomb** [ably/ably-flutter#438]
Implement the changes listed in https://github.com/ably/docs/pull/1526
Reference impl -> https://github.com/ably/ably-js/pull/1045

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4611) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
TODO for `ably-flutter` 
1. Make sure `ably-java` and `ably-cocoa` supports no-connection-serial.
2. Upgrade `ably-flutter` to use latest version of `ably-java` and `ably-cocoa`. 
3. Update `createRecoveryKey` method for both `ably-java` and `ably-cocoa`.
4. Create a PR, merge the same and then create a release.
