### ISSUE TITLE
IOS PUSH notification onTap issue

### ISSUE THREAD

**Issue by Asharulislam** [ably/ably-flutter#440]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.3 21E230 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.71.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

ABLY version: 1.2.12 to 1.2.15

IOS App crash on tapping of notification.

Notification was tapped: Instance of 'RemoteMessage'

* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x16f1bfff0)
    frame #0: 0x0000000192c0ae68 libsystem_malloc.dylib`_malloc_zone_malloc
libsystem_malloc.dylib`_malloc_zone_malloc:
->  0x192c0ae68 <+0>:  stp    x24, x23, [sp, #-0x40]!
    0x192c0ae6c <+4>:  stp    x22, x21, [sp, #0x10]
    0x192c0ae70 <+8>:  stp    x20, x19, [sp, #0x20]
    0x192c0ae74 <+12>: stp    x29, x30, [sp, #0x30]
Target 0: (Runner) stopped.

ikbalkaya

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4613) by [Unito](https://www.unito.io)

**Comment by sohamprodt** [comment]
I am also facing same issue when I tap on notification

**Comment by umair-ably** [comment]
Hi @sohamprodt, this seems to have been a stale issue from nearly 2 years ago. I'm not sure if we've made improvements in this area (the fact that you're also seeing this issue implies we've not fixed it).

Can you share any more detail that would help us replicate this please?

**Comment by sohamprodt** [comment]
Hi @umair-ably  thanks for reaching out. I have solved the error after a research. Thanks
