### ISSUE TITLE
How to handle when user auth changes?

### ISSUE THREAD

**Issue by yahya-uddin** [ably/ably-flutter#459]
Currently I am using authCallback similar as follows:

```
realtime = ably.Realtime(
  options: ably.ClientOptions(
    key: '<API KEY>',
    authCallback: (ably.TokenParams tokenParams) async {
      // authService.token is the currently authenticated user token
      ably.TokenRequest tokenRequest = await createTokenRequest(tokenParams, authService.token);
      return tokenRequest;
    },
  ),
);
```

The issue is how do I handle when the user logs out, and logs back in with another user.

For example are there any methods like:

```
realtime.logout(); 
realtime.login();
```

The current workaround I am using is when the user logs out or changes I close the existing Realtime object, and recreate the Realtime object, so it is forced to re-authorise.

```
realtime.close();
realtime = ably.Realtime(
  options: ably.ClientOptions(
    key: '<API KEY>',
    authCallback: (ably.TokenParams tokenParams) async {
      ably.TokenRequest tokenRequest = await createTokenRequest(tokenParams, authService.token);
      return tokenRequest;
    },
  ),
);
```

**Comment by yahya-uddin** [comment]
It seems like your supposed to use the authorise method:
https://ably.com/docs/api/realtime-sdk/authentication?lang=javascript#authorize

But there seems to be no Flutter equivalant.

Seems like a very common use-case, as a user can log-out and a new user can login any time.

**Comment by yahya-uddin** [comment]
I notice the Auth object is commented out and links to an abstract class:
https://github.com/ably/ably-flutter/blob/1faba4ff8f8a8e434819d48753761b111c8a9b90/lib/src/platform/src/realtime/realtime.dart#L62

**Comment by yahya-uddin** [comment]
Any update on this issue?

**Comment by ikbalkaya** [comment]
Hey @yahya-uddin Sorry about late response on this. I just wanted to let you know that we are aware of this issue and we are going to aim to fix it as soon as possible.
