### ISSUE TITLE
Ably causes runner to crash in XCode 15

### ISSUE THREAD

**Issue by raniel05** [ably/ably-flutter#480]
I updated my simulator to iOS 17 and uses the latest XCode 15 and it seems like ably_flutter plugin is causing the app to crash.

-------------------------------------

`Translated Report (Full Report Below)`
-

`Incident Identifier: C0BCD28B-3A18-4C4B-B256-A59CA67A1FE9`
`CrashReporter Key:   63E056BF-A6D7-4F36-E579-7E979A26D26E`
`Hardware Model:      MacBookAir10,1`
`Process:             Runner [28875]`
`Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/4A8288E0-4C18-4BA1-B7E1-5A545340F8C3/data/Containers/Bundle/Application/59E518EC-2C42-4E6E-8D61-86EA77B4DB65/Runner.app/Runner`
`Identifier:          com.example.testProj`
`Version:             1.0.0 (1)`
`Code Type:           ARM-64 (Native)`
`Role:                Foreground`
`Parent Process:      launchd_sim [1037]`
`Coalition:           com.apple.CoreSimulator.SimDevice.4A8288E0-4C18-4BA1-B7E1-5A545340F8C3 [1170]`
`Responsible Process: SimulatorTrampoline [1024]`

`Date/Time:           2023-09-21 22:39:45.4080 +0800`
`Launch Time:         2023-09-21 22:39:45.3117 +0800`
`OS Version:          macOS 13.5.2 (22G91)`
`Release Type:        User`
`Report Version:      104`

`Exception Type:  EXC_CRASH (SIGABRT)`
`Exception Codes: 0x0000000000000000, 0x0000000000000000`
`Termination Reason: DYLD 4 Symbol missing`
`Symbol not found: `_`OBJC_CLASS`_`$_NSError`
`Referenced from: <0F6D1449-FE01-365E-91C7-063615A4EA66> /Users/USER/Library/Developer/CoreSimulator/Devices/4A8288E0-4C18-4BA1-B7E1-5A545340F8C3/data/Containers/Bundle/Application/59E518EC-2C42-4E6E-8D61-86EA77B4DB65/Runner.app/Frameworks/ably_flutter.framework/ably_flutter`
`Expected in:     <21D37F1A-A952-3927-9A66-03AB5B219B53> /Users/USER/Library/Developer/CoreSimulator/Devices/4A8288E0-4C18-4BA1-B7E1-5A545340F8C3/data/Containers/Bundle/Application/59E518EC-2C42-4E6E-8D61-86EA77B4DB65/Runner.app/Frameworks/Ably.framework/Ably`
`(terminated at launch; ignore backtrace)`

`Triggered by Thread:  0`

`Kernel Triage:`
`VM - (arg = 0x0) pmap_enter retried due to resource shortage`
`VM - (arg = 0x0) pmap_enter retried due to resource shortage`
`VM - (arg = 0x0) pmap_enter retried due to resource shortage`
`VM - (arg = 0x0) pmap_enter retried due to resource shortage`
`VM - (arg = 0x0) pmap_enter retried due to resource shortage`

`Thread 0 Crashed:`
`0   dyld                          	       0x10485f118 __abort_with_payload + 8`
`1   dyld                          	       0x10486ad7c abort_with_payload_wrapper_internal + 104`
`2   dyld                          	       0x10486adb0 abort_with_payload + 16`
`3   dyld_sim                      	       0x104a35f50 abort_with_payload + 40`
`4   dyld_sim                      	       0x1049fc074 dyld4::halt(char const*, dyld4::StructuredError const*) + 300`
`5   dyld_sim                      	       0x1049fa178 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 2504`
`6   dyld_sim                      	       0x1049f93a0 _dyld_sim_prepare + 928`
`7   dyld                          	       0x1047f3d88 dyld4::prepareSim(dyld4::RuntimeState&, char const*) + 1328`
`8   dyld                          	       0x1047f264c dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 276`
`9   dyld                          	       0x1047f1e18 start + 1964`

`Thread 0 crashed with ARM Thread State (64-bit):`
`x0: 0x0000000000000006   x1: 0x0000000000000004   x2: 0x000000016b6eaee0   x3: 0x00000000000001ee`
`x4: 0x000000016b6eaae0   x5: 0x0000000000000000   x6: 0x000000016b6e9980   x7: 0x000000016b6ea540`
`x8: 0x0000000000000020   x9: 0x0000000000000011  x10: 0x0000000000000000  x11: 0x6e206c6f626d7953`
`x12: 0xff786b61402e6a71  x13: 0x0000000000000000  x14: 0x00000001050f8408  x15: 0x000000016b6e9c18`
`x16: 0x0000000000000209  x17: 0x000000000000001e  x18: 0x0000000000000000  x19: 0x0000000000000000`
`x20: 0x000000016b6eaae0  x21: 0x00000000000001ee  x22: 0x000000016b6eaee0  x23: 0x0000000000000004`
`x24: 0x0000000000000006  x25: 0x0000000000000b70  x26: 0x000000016b6ec2b0  x27: 0x0000000000000101`
`x28: 0x000000016b6ed018   fp: 0x000000016b6eaaa0   lr: 0x000000010486ad7c`
`sp: 0x000000016b6eaa60   pc: 0x000000010485f118 cpsr: 0x00001000`
`far: 0x00000001047b8000  esr: 0x56000080  Address size fault`

Already tried creating a new flutter project and only added ably_flutter plugin and crashes also occur.

**Comment by mightyG** [comment]
Same issue on my end.

**Comment by gurhann** [comment]
It is same for me.

**Comment by myoganugraha** [comment]
+1
