### ISSUE TITLE
How do we get connectionId from connection?

### ISSUE THREAD

**Issue by baskillen** [ably/ably-flutter#502]
It looks like the Connection object has an id property, but that and the other properties are not populated (except the state). What is the intended way to populate these fields? Can we somehow help adding these fields? The JS lib seems to properly give us the info we need.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4629) by [Unito](https://www.unito.io)

**Comment by baskillen** [comment]
Any idea when the next version is to be released?

**Comment by sacOO7** [comment]
Hi @baskillen it will be released pretty soon.

**Comment by sacOO7** [comment]
Hi @baskillen we have released fix as a part of v1.2.27, you should bump up the version accordingly 👍
