### ISSUE TITLE
Use constants from platform_constants

### ISSUE THREAD

**Issue by zoechi** [ably/ably-flutter#51]
I saw there exist constants exactly for that, so I thought they should be used here

https://github.com/ably/ably-flutter/blob/fcb392816fbc00cfbcdd3c1766f43468ddd8412a/lib/src/spec/common.dart#L185

https://github.com/ably/ably-flutter/blob/fcb392816fbc00cfbcdd3c1766f43468ddd8412a/lib/src/spec/common.dart#L251

**Comment by tiholic** [comment]
@zoechi the constants that you are referring (generated code) to are used only for transport between dart and platform code.
This map here refers to the JSON response received from Ably Server on making an API call to token request endpoing which gives us a `tokenRequest` json

**Comment by zoechi** [comment]
I see.
