### ISSUE TITLE
Is there a way to respond to Android device battery optimization settings?

### ISSUE THREAD

**Issue by walkerJung** [ably/ably-flutter#513]
On Android devices

Settings Menu -> Application Menu -> Select My App -> Battery Menu

If you go into the menu, there are no restrictions, optimization, and restrictions
I think it's usually set to optimization.

If it's set up like this, the network is disconnected when the app goes to the background, is there a way to respond in ably in this case?

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4673) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
I think library does listen to network state change events => https://github.com/ably/ably-java/blob/main/android/src/main/java/io/ably/lib/platform/AndroidNetworkConnectivity.java. That's why ably goes into disconnected state.

**Comment by walkerJung** [comment]
@sacOO7  I think that's correct. If I fix this, I think I can use it on Android devices without any problems. Thank you so much for your kind answers and guidance
