### ISSUE TITLE
Activate and getting Push Notifications

### ISSUE THREAD

**Issue by srcnysf** [ably/ably-flutter#54]
Is that available to activate and get push notifications with the current SDK ?

@zoechi @tiholic @QuintinWillison

**Comment by QuintinWillison** [comment]
Hello @srcnysf - thanks for raising an issue.

I'm going to check with the team and will get back to you.

(origination: [Intercom](https://app.intercom.com/a/apps/ua39m1ld/inbox/inbox/conversation/38483300001805))

**Comment by QuintinWillison** [comment]
Relates to #107 and #109

**Comment by ben-xD** [comment]
This is work is being done in https://github.com/ably/ably-flutter/issues/107, so I will close this.
