### ISSUE TITLE
FirebaseMessaging.onBackgroundMessage is not called after install ably_flutter: ^1.2.34

### ISSUE THREAD

**Issue by tharro** [ably/ably-flutter#556]
```
@pragma('vm:entry-point')
Future<void> _ablyMessagingBackgroundHandler(ably.RemoteMessage message) async {
  print("Handling a background message: ");
}
```

```
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  print("Handling a background message: ${message.data}");
  await Firebase.initializeApp();
}
```

```
void main() async { 
    WidgetsFlutterBinding.ensureInitialized();
    await Firebase.initializeApp();
    ably.Push.notificationEvents
        .setOnBackgroundMessage(_ablyMessagingBackgroundHandler);
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
    Bloc.observer = SimpleBlocObserver();
    runApp(EasyLocalization(
        supportedLocales: const [Locale('en', 'US')],
        path: 'assets/translations',
        fallbackLocale: const Locale('en', 'US'),
        child: const BlocManager()));
}
```

_ablyMessagingBackgroundHandler also not called

**pubspec.yaml**
  firebase_core: ^2.12.0
  firebase_messaging: ^14.6.0
  firebase_analytics: ^10.4.0
  firebase_crashlytics: ^3.3.0
  flutter_local_notifications: ^17.2.1
  device_info_plus: ^10.0.1
  ably_flutter: ^1.2.34
  
  If I remove ably_flutter, it's working

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-5032) by [Unito](https://www.unito.io)

**Comment by ttypic** [comment]
Hey @tharro,

Thank you very much for reporting this issue! Could you please let us know on which platform this issue occurs—Android, iOS, or both? Additionally, could you share a verbose log from your app? Lastly, does the problem occur immediately after installing ably_flutter, even if `ably.Push.notificationEvents.setOnBackgroundMessage(_ablyMessagingBackgroundHandler);` hasn’t been called?

**Comment by tharro** [comment]
> Hey @tharro,
> 
> Thank you very much for reporting this issue! Could you please let us know on which platform this issue occurs—Android, iOS, or both? Additionally, could you share a verbose log from your app? Lastly, does the problem occur immediately after installing ably_flutter, even if `ably.Push.notificationEvents.setOnBackgroundMessage(_ablyMessagingBackgroundHandler);` hasn’t been called?

Yep, both. The problem occur immediately after installing ably_flutter event if `ably.Push.notificationEvents.setOnBackgroundMessage(_ablyMessagingBackgroundHandler);` hasn’t been called. I will show verbose log soon

**Comment by tharro** [comment]
When I remove 'ably_flutter'. _firebaseMessagingBackgroundHandler is working. If re-install 'ably_flutter', it's not working.

`10.25.0 - [FirebaseAnalytics][I-ACS023220] Analytics screen reporting is enabled. Call Analytics.logEvent(AnalyticsEventScreenView, parameters: [...]) to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
Connecting to VM Service at ws://127.0.0.1:64818/WY61PCmy5PM=/ws
flutter: FCM Token: crIQvIgFDUf0naqG0ipOwN:APA91bGEUuLb8uDA3frtwPixZoYxfw6k4eewn1coWDKnyq_uMujvaLpjxYM6ZRGXVjf1CP_2R37kmZzjdpf3EHt9pULoGh-ZsReGO1kiksFu7NXBtA_EbCW5E6t2EzG3GgQIfT_2GpeK
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Localization initialized<…>
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Start<…>
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Init state<…>
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Build<…>
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Init Localization Delegate<…>
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Init provider<…>
flutter: \^[[34m[🌎 Easy Localization] [WARNING] Localization key [key_press_again_to_exit_app] not found<…>
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Load Localization Delegate<…>
flutter: \^[[90m[🌎 Easy Localization] [DEBUG] Load asset from assets/translations<…>
flutter: SetConversationSelected()
flutter: Handling a background message: {call_id: 83b6e974-4f89-4ca6-a044-80e5ed244e3c, action: CALL, caller: Tharo}`

**Comment by ttypic** [comment]
Hey @tharro,

Sorry for the delayed response. I can reproduce the issue, and we are working on a fix that will be released soon. In the meantime, you can use an older version of the SDK and Flutter. Version < `1.2.34` with Flutter < `3.19` should work fine.

**Comment by tharro** [comment]
@ttypic Thanks for your reply, we can't downgrade for some reason. Please fix and release soon. Our customers are waiting. Many thanks !!!!

**Comment by tharro** [comment]
@ttypic Hello, do you fix the issue?

**Comment by ttypic** [comment]
Hello @tharro,

Apologies for the delay in responding. I’ve explored several approaches to resolve this issue, but unfortunately, I couldn’t find a way to make Ably’s push handler integrate seamlessly with Firebase’s push handler.

However, I recommend using Firebase’s handler if it’s already installed. To address the issue where Firebase stops working after installing ably-flutter, you can disable ably-flutter‘s `BroadcastReceiver`. To do this, please add the following block to your Android application’s manifest file:

```xml
<receiver android:name="io.ably.flutter.plugin.push.FirebaseMessagingReceiver"
                 tools:node="remove">
</receiver>
```

and make sure that your manifest file has tools namespace: 

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
                  xmlns:tools="http://schemas.android.com/tools" ...>
  ...
</manifest>
```
