### ISSUE TITLE
Improve our "pub points" score on pub.dev

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-flutter#65]
We're currently [scoring](https://pub.dev/packages/ably_flutter_plugin/score) **40** out of a possible **110**.

We're also labelled, perhaps as a result of this score, as "**[UNIDENTIFIED]**"... which doesn't sound or look too good!

What can we do to improve this?

**Comment by tiholic** [comment]
@QuintinWillison its due to an installation bug. We need to release a fix addressed in #66
