### ISSUE TITLE
Logging severity required

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-flutter#7]
There are three places where we emit log messages:

- Dart code.
- Objective-C code on iOS runtime.
- Java code on Android runtime.

In all three of those situations we need the ability to log at a severity level appropriate to the message. Plus, of course, we need to be able to switch those log levels in or out at runtime.

**Comment by tiholic** [comment]
@QuintinWillison this is addressed already. I haven't looked into this at all. We can close this.
