### ISSUE TITLE
Unhandled Cast exception happens occasionally when calling channel.subscribe()

### ISSUE THREAD

**Issue by pr-Mais** [ably/ably-flutter#73]
Below is a screenshot of a cast exception that happens sometimes with the channel `subscribe` method.

![Screen Shot 2020-12-09 at 2 33 15 PM](https://user-images.githubusercontent.com/41123719/101648705-25703180-3a4b-11eb-93da-c38157a48939.png)

**Comment by tiholic** [comment]
@pr-Mais can you share more details about the emulator or device this issue was reproduced?

@QuintinWillison Suspecting if the stream is returning faulty data from platform side. Need to investigate more.

> Issue originated from https://github.com/ably/ably-flutter/blob/main/lib/src/impl/realtime/channels.dart#L198 as per the screenshot.

**Comment by pr-Mais** [comment]
I tested on iPhone 12 pro max simulator.

**Comment by QuintinWillison** [comment]
We've been unable to reproduce this issue.

@pr-Mais if you're still facing this then happy to re-open, though in that case we'll need more context (e.g. code to reproduce, details of build environment, more details on runtime environment).
