### ISSUE TITLE
Define Dart API presentation of invalid native plugin state conditions

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-flutter#8]
As pointed out [here](https://github.com/ably/ably-flutter/pull/5#discussion_r419158759), the following comment which is duplicated in a few places needs resolution:

> TODO if ably is nil here then an error response, perhaps? or allow Dart side to understand null response?

This is a fairly key architectural decision so should be documented well.

**Comment by tiholic** [comment]
@QuintinWillison this issue is irrelevant now with singleton Ably instance on either platforms
