### ISSUE TITLE
push notification

### ISSUE THREAD

**Issue by Miamoto-Musashi** [ably/ably-flutter#80]
Hi,
is push notification supported?
is there documentation to follow in order to integrate FCM and APN ?

thanks

**Comment by markcoxsmith** [comment]
Hi @Miamoto-Musashi ,

Unfortunately we don't have currently offer this but we will probably implement this at the future. Keep an eye on the following [](https://github.com/ably/ably-flutter/milestones)

With regards to FCM and APNs, it would integrate as with our other libraries according to the following [docs](https://www.ably.io/documentation/general/push)

**Comment by QuintinWillison** [comment]
Addition of support for push notifications (PN) will now be tracked under #107 (target) and #109 (administration).
