### ISSUE TITLE
Stabilise integration tests when running on Android

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-flutter#92]
On each run of the Android matrix they're failing on at least one of the API levels.

At the time of writing on the latest push to `main` [here](https://github.com/ably/ably-flutter/actions/runs/575919531). Also see [this comment](https://github.com/ably/ably-flutter/pull/89#issuecomment-780788324).

I'm also puzzled, at the time of writing, why the status badge (featured at the top of our readme) states that the `flutter_integration` workflow is `passing` - which it's clearly not. 🤔

**Comment by tiholic** [comment]
@QuintinWillison #93 improves the way integration tests are invoked and executed (either sides of driver) and the failures are very rare. It may still fail in these 2 scenarios:
1. the driver connection between emulator is being lost half way (fiable by attempting re-connection)
2. the emulator would not start (rare - not sure if we can fix it easily, might need us to re-work on the [action](https://github.com/subosito/flutter-action) directly)

Regarding the mismatched status badge, I think we should embed this URL: https://github.com/ably/ably-flutter/actions/workflows/flutter_integration.yaml/badge.svg (best to copy markdown from the [flutter_integation under actions tab](https://github.com/ably/ably-flutter/actions/workflows/flutter_integration.yaml) afresh)

**Comment by QuintinWillison** [comment]
Thanks. 

In terms of the [status badge](https://github.com/ably/ably-flutter/commit/71e84f7821493cdd7acdab87d39d199b705f4c75), this is my fault...

I broke it with [this commit](https://github.com/ably/ably-flutter/commit/b4338c728dcd0bfea029d16716e7a63144c64df2#diff-84b1ffdc3dd9a5bff553d97cd0200a74209a8704061d08622a7fb69cb571ff5e), by removing the explicit name, meaning the workflow path from the perspective of the status badge renderer is different. We're just showing status at the moment for the commits prior to that change!

I still don't want an explicit `name` in the workflow file(s), so the fix going forward will be to update the status badge code in the readme.
